### ISSUE TITLE
Failed to load nodelet [/camera/driver] of type [astra_camera/AstraDriverNodelet]

### ISSUE THREAD

**Issue by Sofiap91** [orbbec/ros_astra_camera#110]
I cloned the package directly from the github repository, as suggested in the closed topic for the same issue. When I launch using roslaunch astra_camera astra.launch, there's the following outcome:

`[ERROR] [1583252306.847184447]: Failed to load nodelet [/camera/driver] of type [astra_camera/AstraDriverNodelet] even after refreshing the cache: Could not find library corresponding to plugin astra_camera/AstraDriverNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1583252306.847381341]: The error before refreshing the cache was: Could not find library corresponding to plugin astra_camera/AstraDriverNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1583252306.848218031]: Failed to load nodelet '/camera/driver` of type `astra_camera/AstraDriverNodelet` to manager `camera_nodelet_manager'
[camera/driver-2] process has died [pid 15459, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load astra_camera/AstraDriverNodelet camera_nodelet_manager ir:=ir rgb:=rgb depth:=depth depth_registered:=depth_registered rgb/image:=rgb/image_raw depth/image:=depth_registered/image_raw __name:=driver __log:=/home/soph/.ros/log/cc8353b4-5d5e-11ea-9275-00e06710abeb/camera-driver-2.log].
log file: /home/soph/.ros/log/cc8353b4-5d5e-11ea-9275-00e06710abeb/camera-driver-2*.log`

I do not really know how to fix this, as I haven't found much infromation about this.
I am using ROS indigo in Ubuntu 14.04. 
Also, catkin_make fails when making this package.

**Comment by mvieira4** [comment]
2 years late but this is caused by missing dependencies. You need to install astra_camera and follow the instructions to download https://wiki.ros.org/astra_camera
