### ISSUE TITLE
Cannot find -lOpenNI2Orbbec

### ISSUE THREAD

**Issue by xiaoyuchhusky** [orbbec/ros_astra_camera#12]
When I did "catkin_make --pkg astra_camera", there was a error that "/usr/bin/ld: cannot find -lOpenNI2Orbbec". Could you please let me know how to fix it?

Thank you very much!

**Comment by jeffhuys** [comment]
Have you fixed it?

**Comment by xiaoyuchhusky** [comment]
@jeffhuys 
Actually, I have closed this question since I found here was not the right place. When I used the code under this repository, no error. The only problem I currently have is that I cannot receive any rgb image data published by the camera. I don't know why!

The error, mentioned in the question, happened when I used another [package](https://github.com/tfoote/ros_astra_camera),
