### ISSUE TITLE
Astra can not publish both (RGB and depth) streams at the same time on ROS Noetic

### ISSUE THREAD

**Issue by brinij** [orbbec/ros_astra_camera#127]
After the successful build and install of the Astra driver on ROS Noetic, I had an issue where RGB and Depth stream could not be published at the same time (Orbbec Astra Mini S used), but only separately. It has the same behavior with libuvc-dev package and libuvc_ros wrapper. Could you please investigate this and report if you have tested your driver with ROS Noetic release?

**Comment by ajcai** [comment]
I have met the same issue, can anyone help?
