### ISSUE TITLE
libOpenNI2.so: file format not recognized; treating as linker script

### ISSUE THREAD

**Issue by tizianrichter** [orbbec/ros_astra_camera#158]
Following the README instructions let to this error when using catkin_make on Noetic:
catkin_ws/src/ros_astra_camera/include/openni2_redist/x64/libOpenNI2.so: file format not recognized; treating as linker script
catkin_ws/src/ros_astra_camera/include/openni2_redist/x64/libOpenNI2.so:1: syntax error
I replaced the libOpenNI2.so file with the one from commit 0d2b91c3decfe6db0401b218f09799e9b8604399 and it worked. Not sure wether I did something wrong while installing though. Maybe someone can look into that and close this issue if there is nothing wrong.

**Comment by jian-dong** [comment]
Hello, @tizianrichter , The problem Is libOpenNI2.so store by git  LFS , Could you please try 
```bash 
sudo apt-get install git-lfs
git lfs install
```
Then  git clone this repo and  try again

**Comment by tizianrichter** [comment]
This worked, thank you :)
