### ISSUE TITLE
Target "libuvc_camera_nodelet" links to target "LibUVC::UVCShared" but the   target was not found.  Perhaps a find_package() call is missing for an   IMPORTED target, or an ALIAS target is missing?

### ISSUE THREAD

**Issue by zyd-123** [orbbec/ros_astra_camera#159]
![image](https://user-images.githubusercontent.com/83893684/181780304-588089a5-a79c-4123-aca3-6ba82af2b29b.png)

**Comment by mintar** [comment]
The same error occurs on Ubuntu 20.04. Could you fix this?

**Comment by jian-dong** [comment]
fixed in commit https://github.com/orbbec/ros_astra_camera/commit/84aa3d5df93efa599034a22ab82253e1fd551ee3
