### ISSUE TITLE
no launch file

### ISSUE THREAD

**Issue by bsbc** [orbbec/ros_astra_camera#17]
Followed the instruction in the README. Compiled the package successfully:
`...`
`[100%] Built target astra_camera_node`
`[100%] Built target astra_camera_nodelet`

However there are no launch files generated. And there is no astra_launch package on astra_camera.

How do you launch the camera with this package?

**Comment by YuehChuan** [comment]
I don't have orbbec, I guess you miss the astra_launch pkgs.
clone it to your catkin_ws
https://github.com/orbbec/ros_astra_launch/blob/master/launch/astra.launch

**Comment by bsbc** [comment]
Thanks
