### ISSUE TITLE
Femto Mega的ROS驱动在哪？

### ISSUE THREAD

**Issue by jiejie567** [orbbec/ros_astra_camera#174]
你好，我想咨询下Femto Mega是否支持ros驱动？更进一步地，是否有支持多个Femto Mega相机同时使用的ROS驱动？

**Comment by jian-dong** [comment]
你好，openNI2的SDK不支持Femto mega,需要使用新的SDK，新的SDK会近期发布在Orbbec[开发者社区](https://developer.orbbec.com.cn/develop_details.html?id=4)
