### ISSUE TITLE
Acquire 1280*960 @ 10FPS RGB image

### ISSUE THREAD

**Issue by davidbsp** [orbbec/ros_astra_camera#18]
Does the driver support exposing an RGB image at 1280*960 @ 10FPS to ROS?

According to the Orbbec Astra Specs (https://orbbec3d.com/product-astra/), this should be possible...

**Comment by ob-tim-liu** [comment]
modify astra.cfg to 1280*1024, you can get 1280*960@7fps, and due to the limit of usb2.0 , you can choice 160x120 depth at same time

**Comment by davidbsp** [comment]
Thanks. I used rqt_reconfigure to change the color_mode to "SXGA_30Hz" on the run. Got ~6.5 Hz.
