### ISSUE TITLE
Internet connction needed for every build

### ISSUE THREAD

**Issue by romainreignier** [orbbec/ros_astra_camera#19]
It is quite annoying that the package needs an internet connection at every build to download OpenNI2.
I am using Astra cameras on a mobile robot that is not always connected to internet so I cannot build my whole Ros workspace.

**Comment by romainreignier** [comment]
In the meantime, I use this answer as a workaround:
http://stackoverflow.com/a/40423683

**Comment by ob-tim-liu** [comment]
you can use branch - filterlibrary

**Comment by romainreignier** [comment]
Ok, thanks for the tip!
