### ISSUE TITLE
Depth Color synchronization in ros?

### ISSUE THREAD

**Issue by naterod** [orbbec/ros_astra_camera#24]
Hi, 
Does anyone know how to get the color and depth image published on a single topic so that the images line up in time? As far as i can tell the color and depth time stamps do not match up. I have turned on all the depth_registration flags. And get this when running astra launch:
PARAMETERS
* /camera/camera_nodelet_manager/num_worker_threads: 4
* /camera/depth_rectify_depth/interpolation: 0
* /camera/depth_registered_rectify_depth/interpolation: 0
* /camera/driver/auto_exposure: True
* /camera/driver/auto_white_balance: True
* /camera/driver/color_depth_synchronization: True
* /camera/driver/depth_camera_info_url: 
* /camera/driver/depth_frame_id: camera_depth_opti...
* /camera/driver/depth_registration: True
* /camera/driver/device_id: #1
* /camera/driver/rgb_camera_info_url: 
* /camera/driver/rgb_frame_id: camera_rgb_optica...
* /rosdistro: indigo
* /rosversion: 1.11.21

the topic /camera/depth_registered/points has 8 channels for pixel where the first 3 are x,y,z coordinates but the remaining 5 values are always 0 or NaN.

Has anyone managed to get get corresponding frames?

**Comment by richardw347** [comment]
There is mention of hardware sync in this [forum post](https://3dclub.orbbec3d.com/t/rgb-d-synchronization-on-ros/784) but the link to the firmware update is broken and it's not clear if this was ever working with the ROS version of their driver.

Can we get an update on this please?
