### ISSUE TITLE
provide a firmware updater script

### ISSUE THREAD

**Issue by tfoote** [orbbec/ros_astra_camera#5]
There's some documentation here: https://3dclub.orbbec3d.com/t/rgb-d-sync-project/265 of how to update the firmware. 

A simple script which can be provided by the package and can flash the firmware onto the devices intellegently. 

It should know compatibility and refuse to flash incompatible firmware. And it would be great if it could query the firmware version and know what the versions available are and how to fetch them.

**Comment by ob-tim-liu** [comment]
add fwupgrade script on  fwupgrade dir.
