### ISSUE TITLE
Not working with ROS Melodic

### ISSUE THREAD

**Issue by DonSlaughter** [orbbec/ros_astra_camera#61]
I get the following error messages when I try to compile ros_astra_camera :

`[ 40%] Performing configure step for 'astra_openni2'
no need to configure
[ 43%] Performing build step for 'astra_openni2'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:40: HOST_PLATFORM is x64
../../BuildSystem/CommonDefs.mak:40: HOST_PLATFORM is x64
../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:40: HOST_PLATFORM is x64
../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:40: HOST_PLATFORM is x64
../../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak:40: HOST_PLATFORM is x64
Formats/XnFormatsMirror.cpp: In function ‘XnStatus XnMirrorOneBytePixels(XnUChar*, XnUInt32, XnUInt32)’:
Formats/XnFormatsMirror.cpp:46:11: error: array subscript is below array bounds [-Werror=array-bounds]
  XnUInt8* pDestEnd = &pLineBuffer[0] - 1;
           ^~~~~~~~
Formats/XnFormatsMirror.cpp: In function ‘XnStatus XnMirrorTwoBytePixels(XnUChar*, XnUInt32, XnUInt32)’:
Formats/XnFormatsMirror.cpp:79:12: error: array subscript is below array bounds [-Werror=array-bounds]
  XnUInt16* pDestEnd = &pLineBuffer[0] - 1;
            ^~~~~~~~
Formats/XnFormatsMirror.cpp: In function ‘XnStatus XnMirrorThreeBytePixels(XnUChar*, XnUInt32, XnUInt32)’:
Formats/XnFormatsMirror.cpp:115:11: error: array subscript is below array bounds [-Werror=array-bounds]
  XnUInt8* pDestEnd = &pLineBuffer[0] - 1;
           ^~~~~~~~
cc1plus: all warnings being treated as errors
../../../ThirdParty/PSCommon/BuildSystem/CommonCppMakefile:141: recipe for target '../../../Bin/Intermediate/x64-Release/liborbbec.so/XnFormatsMirror.o' failed
make[4]: *** [../../../Bin/Intermediate/x64-Release/liborbbec.so/XnFormatsMirror.o] Error 1
Makefile:131: recipe for target 'Source/Drivers/orbbec' failed
make[3]: *** [Source/Drivers/orbbec] Error 2
ros_astra_camera/CMakeFiles/astra_openni2.dir/build.make:110: recipe for target 'ros_astra_camera/astra_openni2/src/astra_openni2-stamp/astra_openni2-build' failed
make[2]: *** [ros_astra_camera/astra_openni2/src/astra_openni2-stamp/astra_openni2-build] Error 2
CMakeFiles/Makefile2:1018: recipe for target 'ros_astra_camera/CMakeFiles/astra_openni2.dir/all' failed
make[1]: *** [ros_astra_camera/CMakeFiles/astra_openni2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

I have ros_astra_cam and usb_cam with the launch file from the other astra git in my catkin_astra/src directory.
It's the same I have with my other Ubuntu system except that the other one is a Mint 18.3 with ROS Kinetic and now its Mint 19 with ROS Melodic

**Comment by mzwang828** [comment]
Hi, 
Have you solved this problem? I'm having the same error with ROS Melodic

**Comment by BreakingLaw** [comment]
anyone can solve this problem?, im working with ros melodic too.

**Comment by Nan-Orbbec3d-US** [comment]
Hi guys, could you try the latest version again. I try to build it with melodic + ubuntu 18.04 and it works. If you still have the same error, please let me know.

**Comment by NikolasE** [comment]
Works for me on Melodic

**Comment by Nan-Orbbec3d-US** [comment]
@NikolasE Cool, I would like to close this. If anyone has problem on Melodic, feel free to reopen it.

**Comment by ANABUR920** [comment]
still cannot work on ubuntu 18 + melodic, and the same error

**Comment by Nan-Orbbec3d-US** [comment]
Could you check the version of the package? According to the log, the build system tried to build XnLib and PSCommon which were removed after 0.3.0.

**Comment by bonedoz** [comment]
@Nan-Orbbec3d-US Can't work on `ROS Melodic` & `GCC 7.5.0` with the latest version of the package.

**Comment by KIYOLY** [comment]
this still happens to me
(jetson nano, melodic)
