### ISSUE TITLE
All rgb topics are empty

### ISSUE THREAD

**Issue by frushton** [orbbec/ros_astra_camera#66]
When I launch the astrapro.launch file and do a 'rostopic list', it lists all of the depth, ir, and rgb topics. The depth and ir topics are being published to, and I can view the image feed. However, the rgb topics are all empty. This is the terminal I launch the launch file in:

roslaunch astrapro.launch 
... logging to /home/e4e/.ros/log/ccfe7e6a-cdb6-11e8-af2b-9cb6d0dcfaeb/roslaunch-e4e-XPS-15-9560-24406.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://e4e-XPS-15-9560:42871/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/driver/auto_exposure: True
 * /camera/driver/auto_white_balance: True
 * /camera/driver/bootorder: 0
 * /camera/driver/color_depth_synchronization: False
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/devnums: 1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    driver (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_base_link (tf/static_transform_publisher)
    camera_base_link1 (tf/static_transform_publisher)
    camera_base_link2 (tf/static_transform_publisher)
    camera_base_link3 (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [24416]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ccfe7e6a-cdb6-11e8-af2b-9cb6d0dcfaeb
process[rosout-1]: started with pid [24429]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [24441]
process[camera/driver-3]: started with pid [24447]
process[camera/rgb_debayer-4]: started with pid [24448]
process[camera/rgb_rectify_mono-5]: started with pid [24456]
process[camera/rgb_rectify_color-6]: started with pid [24469]
process[camera/depth_rectify_depth-7]: started with pid [24475]
process[camera/depth_metric_rect-8]: started with pid [24487]
process[camera/depth_metric-9]: started with pid [24497]
[ INFO] [1539304564.836762739]: Initializing nodelet with 4 worker threads.
process[camera/depth_points-10]: started with pid [24511]
process[camera/register_depth_rgb-11]: started with pid [24528]
process[camera/points_xyzrgb_sw_registered-12]: started with pid [24553]
process[camera/depth_registered_sw_metric_rect-13]: started with pid [24564]
process[camera_base_link-14]: started with pid [24581]
process[camera_base_link1-15]: started with pid [24590]
process[camera_base_link2-16]: started with pid [24602]
process[camera_base_link3-17]: started with pid [24612]
[ INFO] [1539304564.936147051]: Device "2bc5/0403@1/8" found.
^C[camera_base_link3-17] killing on exit
[camera_base_link2-16] killing on exit
[camera_base_link1-15] killing on exit
[camera_base_link-14] killing on exit
[camera/depth_registered_sw_metric_rect-13] killing on exit
[camera/points_xyzrgb_sw_registered-12] killing on exit
[camera/register_depth_rgb-11] killing on exit
[camera/depth_points-10] killing on exit
[camera/depth_metric-9] killing on exit
[camera/depth_metric_rect-8] killing on exit
[camera/depth_rectify_depth-7] killing on exit
[camera/rgb_rectify_color-6] killing on exit
[camera/rgb_rectify_mono-5] killing on exit
[camera/rgb_debayer-4] killing on exit
[camera/driver-3] killing on exit
[camera/camera_nodelet_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Do you know what may be causing this?

**Comment by vishu2287** [comment]
hello @frushton . i am encountering same problem. May i know if it has been solved?

**Comment by frushton** [comment]
Hello @vishu2287, it seems that the problem comes from the fact that the rgb stream of the Astra Pro camera is only accessible through the UVC interface. This link discusses this problem, and offers some potential solutions that I have not tried yet. 

https://3dclub.orbbec3d.com/t/compatibility-astra-pro-and-openni2/108/2

**Comment by Nan-Orbbec3d-US** [comment]
Hi @frushton , @vishu2287 , could you try the latest version again. Thank you!

**Comment by Nan-Orbbec3d-US** [comment]
fixed after commit 67a44c44105eb4c86d3a8476a10f8c54ef1f0895
