### ISSUE TITLE
libuvc_camera_nodelet.xml missing

### ISSUE THREAD

**Issue by NikolasE** [orbbec/ros_astra_camera#75]
The CMakelists wants to install libuvc_camera_nodelet.xml which I can't find in the repository. The install command was added in https://github.com/orbbec/ros_astra_camera/commit/efd14c789e2dcfe2ff5c3e4c7fbad19db7c3db85.

install(FILES libuvc_camera_nodelet.xml
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
)

**Comment by Nan-Orbbec3d-US** [comment]
It shouldn't exist. I've already removed those two lines. Did you encounter any issues while compiling?

**Comment by NikolasE** [comment]
No, the rest worked nicely :)
