### ISSUE TITLE
High resolution IR image on stereo S

### ISSUE THREAD

**Issue by coxep** [orbbec/ros_astra_camera#81]
Is there a way to get a high resolution (XGA or higher) IR image on the stereo S? I'm interested in performing extrinsic calibration, but the 640x400 resolution is too small.

**Comment by Nan-Orbbec3d-US** [comment]
Hi, I add a few more resolutions in the latest version. If you want to use higher resolution, you should
1. turn off uvc camera in `stereo_s.launch`
2. launch stereo_s.
3. run rqt_reconfigure and switch ir_mode to **16**.
Then you should be able to get higher resolution ir at around 7fps.

**Comment by coxep** [comment]
Ahh, aawesome! Thank you!!!
