### ISSUE TITLE
Error in the examples

### ISSUE THREAD

**Issue by MarioEstebanOchoa** [orbbec/ros_astra_camera#82]
in the examples `roslaunch astra_camera astra.launch` and `roslaunch astra_camera stereo_s.launch` the name of the package is still astra_launch, and that is producing errors when executing
So, change the name in the files.

**Comment by Nan-Orbbec3d-US** [comment]
Thank you for your reply. Fixed in commit 3462dbfb961595f699c1cb4ad22d535896efb1f8.
