### ISSUE TITLE
rviz sometimes can't display pointcloud2

### ISSUE THREAD

**Issue by Thuan98** [orbbec/ros_astra_camera#87]
when i run : roscore, rosrun astra_camera astra_camera_node , roslaunch astra_launch astrapro.launch

**Comment by Nan-Orbbec3d-US** [comment]
Hi @Thuan98 , could you provide more detailed information like the log? BTW, if you are working on a single computer, you can just use one command `roslaunch astra_camera astrapro.launch` to launch your astrapro.

**Comment by Thuan98** [comment]
i use it on jetson tx2, but i can't visualize pointcloud2 on rviz. Status: received message,contains invalid floating point values (nans or infs) on camera.pointcloud2 also received message but not display

**Comment by Nan-Orbbec3d-US** [comment]
Did you receive any specific error messages? So your procedure is
1. launch astrapro
2. echo topic `/camera/depth_registered/points`
3. get nans/infs
Is this correct?

**Comment by iamzhuang** [comment]
I used the astro pro to run in ros...I could dispaly rgb and depth..but there was not any pointcloud to display in rviz..the rviz display the pointcloud2 topic messages is received,but not display in it.



spark@spark:~/astra_pro_ws/src/ros_astra_camera/launch$ roslaunch astra_camera astrapro.launch 
... logging to /home/spark/.ros/log/8eff2306-bcb4-11e9-8f3f-e4029b917850/roslaunch-spark-18939.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://spark:32993/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/camera_rgb/camera_info_url: 
 * /camera/camera_rgb/frame_rate: 30
 * /camera/camera_rgb/height: 480
 * /camera/camera_rgb/index: 0
 * /camera/camera_rgb/product: 0x0501
 * /camera/camera_rgb/serial: 0
 * /camera/camera_rgb/timestamp_method: start
 * /camera/camera_rgb/vendor: 0x2bc5
 * /camera/camera_rgb/video_mode: yuyv
 * /camera/camera_rgb/width: 640
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/driver/auto_exposure: True
 * /camera/driver/auto_white_balance: True
 * /camera/driver/bootorder: 0
 * /camera/driver/color_depth_synchronization: False
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: True
 * /camera/driver/device_id: #1
 * /camera/driver/devnums: 1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    camera_rgb (astra_camera/camera_node)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    driver (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
  /
    camera_base_link (tf/static_transform_publisher)
    camera_base_link1 (tf/static_transform_publisher)
    camera_base_link2 (tf/static_transform_publisher)
    camera_base_link3 (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [18949]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8eff2306-bcb4-11e9-8f3f-e4029b917850
process[rosout-1]: started with pid [18962]
started core service [/rosout]
process[camera/camera_rgb-2]: started with pid [18979]
process[camera/camera_nodelet_manager-3]: started with pid [18980]
process[camera/driver-4]: started with pid [18981]
process[camera/rgb_rectify_color-5]: started with pid [18991]
process[camera/depth_rectify_depth-6]: started with pid [19002]
process[camera/depth_metric_rect-7]: started with pid [19013]
process[camera/depth_metric-8]: started with pid [19024]
process[camera/depth_points-9]: started with pid [19031]
process[camera/depth_registered_rectify_depth-10]: started with pid [19040]
process[camera/points_xyzrgb_hw_registered-11]: started with pid [19055]
process[camera/depth_registered_hw_metric_rect-12]: started with pid [19065]
[ INFO] [1565581930.579046471]: Initializing nodelet with 4 worker threads.
process[camera/depth_registered_metric-13]: started with pid [19084]
process[camera_base_link-14]: started with pid [19097]
process[camera_base_link1-15]: started with pid [19106]
process[camera_base_link2-16]: started with pid [19109]
process[camera_base_link3-17]: started with pid [19122]
      564 INFO       New log started on 2019-08-12 11:52:10
      582 INFO       --- Filter Info --- Minimum Severity: VERBOSE
     1203 VERBOSE    OpenNI 2.3.0 (Build 63)-Linux-x86 (May 13 2019 15:00:00)
     1231 VERBOSE    Configuration file found at '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI.ini'
     1298 VERBOSE    Using '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers' as driver path
     1304 VERBOSE    Looking for drivers at '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers'
     1643 VERBOSE    Loading device driver 'libOniFile.so'...
     1662 WARNING    loading lib from: /home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/libOniFile.so

     1998 VERBOSE    Loading device driver 'libPSLink.so'...
     2077 WARNING    loading lib from: /home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/libPSLink.so

     4427 WARNING    LibraryHandler: Couldn't find function oniDriverStreamConvertC2DCoordinates in libPSLink.so. Stopping
     4539 WARNING    Couldn't use file 'libPSLink.so' as a device driver
     4599 VERBOSE    Loading device driver 'liborbbec.so'...
     4646 WARNING    loading lib from: /home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/liborbbec.so

     5700 INFO       New log started on 2019-08-12 11:52:10
     5717 INFO       --- Filter Info --- Minimum Severity: VERBOSE
     5732 VERBOSE    Initializing USB...
    13659 INFO       USB is initialized.
    13747 INFO       Device connected: Orbbec Astra (2bc5/0403@2/14)
[ INFO] [1565581930.708898179]: Device "2bc5/0403@2/14" found.
   108354 VERBOSE    Initialize: Already initialized
   108452 VERBOSE    Trying to open device by URI '2bc5/0403@2/14'
   109369 VERBOSE    Initializing device sensor...
   109478 VERBOSE    Configuring module 'Device' from section 'Device' in file '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/orbbec.ini'...
   109563 INFO       Setting Device.UsbInterface to 2...
   109573 INFO       Device.UsbInterface value did not change.
   110274 INFO       Module 'Device' configuration was loaded from file.
   110298 VERBOSE    Connecting to USB device...
   110308 VERBOSE    Trying to open sensor '2bc5/0403@2/14'...
   110438 INFO       USB is high Speed
   110452 VERBOSE    Starting libusb asynch thread...
   110543 WARNING    Failed to set thread priority (1)
   110552 WARNING    USB events thread: Failed to set thread priority to critical. This might cause loss of data...
Warning: USB events thread - failed to set priority. This might cause loss of data...
   110565 VERBOSE    Trying to open endpoint 0x4 for control out (for old firmwares)...
   110635 INFO       Connected to USB device
   119196 VERBOSE    Getting hardware versions...
   130712 INFO       Hardware versions: FW=5.8.22 (14) HW=0 Chip=0 Sensor=0 SYS=12
   142058 WARNING    Received NACK: 2
   142108 INFO       Reading CMOS 0 supported presets...
   142716 VERBOSE    Requesting KeepAlive...
   142991 VERBOSE    Got KeepAlive Reply.
   143000 VERBOSE    Setting mode to 3...
   144348 VERBOSE    Requesting KeepAlive...
   144623 VERBOSE    Got KeepAlive Reply.
   144927 VERBOSE    Getting the fixed params...
   145301 INFO       Reading sensor serial number...
   145611 VERBOSE    Sensor serial number: 17091100235
   145623 VERBOSE    Getting algorithm params 0x7 for resolution 0 and fps 0....
   145963 INFO       Reading sensor platform string...
   146301 VERBOSE    Property Firmware.ReferenceResolution was changed to 2.
   146313 VERBOSE    Reading all params from firmware...
   147565 VERBOSE    Property Firmware.ImageBacklightCompensation (79) was changed to 1.
   148269 VERBOSE    Property Firmware.DepthResolution (19) was changed to 1.
   154288 VERBOSE    Property Firmware.ImageAutoWhiteBalance (77) was changed to 1.
   155075 VERBOSE    Property Firmware.ImageLowLightCompensation (82) was changed to 1.
   156472 VERBOSE    Property Firmware.DepthHoleFilter (22) was changed to 1.
   158630 VERBOSE    Property Firmware.ImageFPS (14) was changed to 30.
   158916 VERBOSE    Property Firmware.GMCMode (36) was changed to 1.
   159448 VERBOSE    Property Firmware.ImageAutoExposure (80) was changed to 1.
   159739 VERBOSE    Property Firmware.DepthFPS (20) was changed to 30.
   160557 VERBOSE    Property Firmware.DepthWhiteBalance (45) was changed to 1.
   161407 VERBOSE    Property Firmware.ImageFormat (12) was changed to 5.
   162456 VERBOSE    Property Firmware.DepthFormat (18) was changed to 3.
   162749 VERBOSE    Property Firmware.ImageGain (15) was changed to 128.
   164961 VERBOSE    Property Firmware.ImageQuality (16) was changed to 3.
   165271 VERBOSE    Property Firmware.ImageSharpness (76) was changed to 32.
   165843 VERBOSE    Property Firmware.ImageExposureBar (81) was changed to 1.
   166121 VERBOSE    Property Firmware.DepthGain (21) was changed to 42.
   167991 VERBOSE    Firmware params were updated.
   168070 INFO       Property Device.PhysicalDeviceName was changed to ORBBEC ASTRA Pro.
   168081 INFO       Property Device.VendorData was changed to ASTRA Depth Sensor.
   168089 INFO       Property Device.ID was changed to 17091100235.
   168095 INFO       Property Device.SensorPlatformString was changed to RD108C-009.
   168445 WARNING    Received NACK: 65535
   168501 ERROR      Support sub cmd error!
   168516 INFO       Device sensor initialized
   248715 INFO       Creating stream 'IR' of type 'IR'...
   248735 INFO       Setting Device.ReadData to 1...
   248815 VERBOSE    Setting USB alternative interface to 0...
   249166 VERBOSE    Opening endpoints...
   249174 VERBOSE    Opening endpoint 0x81 for depth...
   249250 VERBOSE    Depth endpoint is bulk.
   249257 VERBOSE    Opening endpoint 0x82 for image...
   249304 VERBOSE    Image endpoint is bulk.
   249311 VERBOSE    Opening endpoint 0x83 for misc...
   249345 VERBOSE    Misc endpoint is not supported...
   249350 INFO       Endpoints open
   249399 VERBOSE    Getting algorithm params 0x80 for resolution 0 and fps 0....
   249950 INFO       Property Device.ReadData was changed to 1.
   249967 INFO       Reading CMOS 0 supported presets...
   250288 INFO       Device.ReadData was successfully set.
   250481 VERBOSE    Initializing stream 'IR'...
   250517 INFO       Property IR.Resolution was changed to QVGA.
   250525 INFO       Property IR.XRes was changed to 320.
   250530 INFO       Property IR.YRes was changed to 240.
   250536 INFO       Property IR.FPS was changed to 30.
   250540 INFO       Property IR.OutputFormat was changed to 203.
   250545 INFO       Property IR.BytesPerPixel was changed to 2.
   250550 INFO       Property IR.RequiredDataSize was changed to 158720.
   250558 INFO       Property IR.SupportedModesCount was changed to 17.
   250565 INFO       Property IR.Mirror was changed to 1.
   250571 INFO       Stream 'IR' was initialized.
   250576 INFO       'IR' stream was created.
   250581 VERBOSE    Configuring module 'IR' from section 'IR' in file '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/orbbec.ini'...
   250887 INFO       Setting IR.Resolution to 640x400...
   250897 INFO       Property IR.Resolution was changed to 640x400.
   250905 INFO       Property IR.XRes was changed to 640.
   250912 INFO       Property IR.RequiredDataSize was changed to 317440.
   250919 INFO       Property IR.YRes was changed to 400.
   250925 INFO       Property IR.RequiredDataSize was changed to 522240.
   250932 INFO       IR.Resolution was successfully set.
   251054 INFO       Module 'IR' configuration was loaded from file.
   251513 INFO       Setting IR.OutputFormat to 203...
   251524 INFO       IR.OutputFormat value did not change.
   251532 INFO       Setting IR.FPS to 30...
   251537 INFO       IR.FPS value did not change.
   251543 INFO       Setting IR.XRes to 640...
   251548 INFO       IR.XRes value did not change.
   251554 INFO       Setting IR.YRes to 480...
   251561 INFO       Property IR.Resolution was changed to VGA.
   251571 INFO       Property IR.YRes was changed to 480.
   251578 INFO       Property IR.RequiredDataSize was changed to 624640.
   251588 INFO       IR.YRes was successfully set.
   251690 INFO       Creating stream 'Depth' of type 'Depth'...
   252085 VERBOSE    Initializing stream 'Depth'...
   252131 INFO       Property Depth.OutputFormat was changed to 100.
   252142 INFO       Property Depth.BytesPerPixel was changed to 2.
   252148 INFO       Property Depth.RequiredDataSize was changed to 614400.
   252200 INFO       Property Depth.MaxDepth was changed to 65534.
   252267 INFO       Property Depth.SupportedModesCount was changed to 47.
   252285 INFO       Property Depth.Resolution was changed to QVGA.
   252306 INFO       Property Depth.XRes was changed to 320.
   252327 INFO       Property Depth.RequiredDataSize was changed to 307200.
   252339 INFO       Property Depth.YRes was changed to 240.
   252350 INFO       Property Depth.RequiredDataSize was changed to 153600.
   252358 INFO       Property Depth.FPS was changed to 30.
   252370 INFO       Property Depth.ParamCoeff was changed to 4.
   252420 INFO       Property Depth.ShiftScale was changed to 10.
   252490 VERBOSE    Getting algorithm params 0x0 for resolution 1 and fps 30....
   253150 INFO       Property Depth.ConstShift was changed to 200.
   253232 INFO       Property Depth.ZPD was changed to 130.000000.
   253277 INFO       Property Depth.ZPPS was changed to 0.113967.
   253282 INFO       Property Depth.LDDIS was changed to 7.500000.
   253322 INFO       Property Depth.DCRCDIS was changed to 2.630000.
   253823 INFO       Property Depth.HorizontalFov was changed to 1.022600.
   253872 INFO       Property Depth.VerticalFov was changed to 0.796616.
   254134 VERBOSE    cmostype: 1 m_VerticalFOV: 0.796616, m_HorizontalFOV: 1.022600
   254160 INFO       Property Depth.Gain was changed to 42.
   254209 VERBOSE    Getting algorithm params 0x2 for resolution 4 and fps 30....
   254638 VERBOSE    Getting algorithm params 0x2 for resolution 0 and fps 30....
   254957 VERBOSE    Getting algorithm params 0x2 for resolution 1 and fps 30....
   255303 VERBOSE    Getting algorithm params 0x3 for resolution 4 and fps 30....
   255575 VERBOSE    Getting algorithm params 0x3 for resolution 0 and fps 30....
   255834 VERBOSE    Getting algorithm params 0x3 for resolution 1 and fps 30....
   304015 INFO       Property Depth.FirmwareMirror was changed to 1.
   304075 INFO       Property Depth.Mirror was changed to 1.
   304131 INFO       Stream 'Depth' was initialized.
   304165 INFO       'Depth' stream was created.
   304189 VERBOSE    Configuring module 'Depth' from section 'Depth' in file '/home/spark/astra_pro_ws/src/ros_astra_camera/include/openni2_redist/x64/OpenNI2/Drivers/orbbec.ini'...
   304414 INFO       Setting Depth.InputFormat to 3...
   304443 INFO       Depth.InputFormat was successfully set.
   305261 INFO       Setting Depth.Resolution to 640x400...
   305273 INFO       Property Depth.Resolution was changed to 640x400.
   305285 INFO       Property Depth.XRes was changed to 640.
   305292 INFO       Property Depth.RequiredDataSize was changed to 307200.
   305299 INFO       Property Depth.YRes was changed to 400.
   305305 INFO       Property Depth.RequiredDataSize was changed to 512000.
   305312 INFO       Depth.Resolution was successfully set.
   305557 INFO       Module 'Depth' configuration was loaded from file.
   305764 INFO       Setting Depth.OutputFormat to 100...
   305774 INFO       Depth.OutputFormat value did not change.
   305782 INFO       Setting Depth.FPS to 30...
   305787 INFO       Depth.FPS value did not change.
   305792 INFO       Setting Depth.XRes to 640...
   305799 INFO       Depth.XRes value did not change.
   305804 INFO       Setting Depth.YRes to 480...
   305825 INFO       Property Depth.Resolution was changed to VGA.
   305844 INFO       Property Depth.YRes was changed to 480.
   305861 INFO       Property Depth.RequiredDataSize was changed to 614400.
   305877 INFO       Depth.YRes was successfully set.
   305953 INFO       Setting Depth.Registration to 1...
   305961 INFO       Property Depth.FirmwareRegistration was changed to 1.
   305968 INFO       Property Depth.Registration was changed to 1.
   305974 INFO       Depth.Registration was successfully set.
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
attempt to claim already-claimed interface 1
[ INFO] [1565581945.299011969]: Starting depth stream.
 14605107 INFO       Setting Depth.Mirror to 0...
 14605132 INFO       Property Depth.FirmwareMirror was changed to 0.
 14605142 INFO       Property Depth.Mirror was changed to 0.
 14605151 INFO       Depth.Mirror was successfully set.
 14605178 VERBOSE    FW Stream Depth was claimed by Depth
 14605191 VERBOSE    Creating USB depth read thread...
 14605197 VERBOSE    Starting a USB read thread...
 14606415 INFO       USB read thread was started.
 14606447 WARNING    Failed to set thread priority (1)
 14606470 INFO       Property Depth.ActualReadData was changed to 1.
 14606483 VERBOSE    Setting Firmware.DepthFormat (18) to 3...
 14606507 WARNING    Failed to set thread priority to critical. This might cause loss of data...
 14607427 VERBOSE    Firmware.DepthFormat (18) was successfully set.
 14607455 VERBOSE    Setting Firmware.DepthResolution (19) to 1...
 14609062 VERBOSE    Firmware.DepthResolution (19) was successfully set.
 14609077 VERBOSE    Setting Firmware.DepthFPS (20) to 30...
 14609409 VERBOSE    Firmware.DepthFPS (20) was successfully set.
 14609419 VERBOSE    Setting Firmware.DepthHoleFilter (22) to 1...
 14609832 VERBOSE    Firmware.DepthHoleFilter (22) was successfully set.
 14609853 VERBOSE    Setting Firmware.DepthGain (21) to 42...
 14610164 VERBOSE    Firmware.DepthGain (21) was successfully set.
 14610175 VERBOSE    Setting Firmware.DepthDecimation (24) to 0...
 14610535 VERBOSE    Firmware.DepthDecimation (24) was successfully set.
 14610545 VERBOSE    Setting Firmware.Registration (2) to 1...
 14610840 VERBOSE    Property Firmware.Registration (2) was changed to 1.
 14610861 VERBOSE    Firmware.Registration (2) was successfully set.
 14610870 VERBOSE    Setting Firmware.DepthMirror (23) to 0...
 14611213 VERBOSE    Firmware.DepthMirror (23) was successfully set.
 14611222 VERBOSE    Setting Firmware.GMCMode (36) to 1...
 14611515 VERBOSE    Firmware.GMCMode (36) was successfully set.
 14611522 VERBOSE    Setting Firmware.GMCDebug (61) to 0...
 14611796 VERBOSE    Firmware.GMCDebug (61) was successfully set.
 14611809 VERBOSE    Setting Firmware.WavelengthCorrection (73) to 0...
 14612162 VERBOSE    Firmware.WavelengthCorrection (73) was successfully set.
 14612174 VERBOSE    Setting Firmware.WavelengthCorrectionDebug (74) to 0...
 14612469 VERBOSE    Firmware.WavelengthCorrectionDebug (74) was successfully set.
 14612483 VERBOSE    Setting Firmware.DepthWhiteBalance (45) to 1...
 14612785 VERBOSE    Firmware.DepthWhiteBalance (45) was successfully set.
 14612795 VERBOSE    Getting algorithm params 0x6 for resolution 1 and fps 30....
 14613254 VERBOSE    Read flash distortion enable state 0
 14613267 VERBOSE    Multi distance calibration enable 0
 14613274 WARNING    Sensor params invalid(NaN value)

 14613289 VERBOSE    Firmware stream 'Depth' processor was replaced.
 14613296 VERBOSE    Getting algorithm params 0x80 for resolution 0 and fps 0....
 14613650 VERBOSE    Setting Firmware.Stream1Mode (6) to 2...
 14618964 VERBOSE    Property Firmware.Stream1Mode (6) was changed to 2.
 14619072 VERBOSE    Setting Firmware.FrameSync (1) to 0...
 14624300 VERBOSE    Firmware.FrameSync (1) was successfully set.
 14624321 VERBOSE    Firmware.Stream1Mode (6) was successfully set.
 14624327 VERBOSE    Setting Firmware.CloseRange (84) to 0...
 14624688 VERBOSE    Firmware.CloseRange (84) was successfully set.
 14624697 VERBOSE    Setting Firmware.DepthCropEnabled (55) to 0...
 14625021 VERBOSE    Firmware.DepthCropEnabled (55) was successfully set.
 14625029 INFO       Property Depth.State was changed to 1.
 14688102 WARNING    Depth: Expected 1, got b43f
 14688198 WARNING    Depth frame is corrupt!
 14727364 VERBOSE    [FPS] IR: 0.00 Depth: 0.00 
[ INFO] [1565581945.422387886]: using default calibration URL
[ INFO] [1565581945.422482302]: camera calibration URL: file:///home/spark/.ros/camera_info/depth_Astra_Orbbec.yaml
[ INFO] [1565581945.422629219]: Unable to open camera calibration file [/home/spark/.ros/camera_info/depth_Astra_Orbbec.yaml]
[ WARN] [1565581945.422706374]: Camera calibration file /home/spark/.ros/camera_info/depth_Astra_Orbbec.yaml not found.
 15027559 VERBOSE    [FPS] IR: 0.00 Depth: 33.31 
 16003312 VERBOSE    [FPS] IR: 0.00 Depth: 30.56 
 17011455 VERBOSE    [FPS] IR: 0.00 Depth: 30.21 
 18027188 VERBOSE    [FPS] IR: 0.00 Depth: 30.00 
 19003621 VERBOSE    [FPS] IR: 0.00 Depth: 30.01 
 20011290 VERBOSE    [FPS] IR: 0.00 Depth: 30.00 
 21026374 VERBOSE    [FPS] IR: 0.00 Depth: 30.01 
 22002047 VERBOSE    [FPS] IR: 0.00 Depth: 30.02 
 23009457 VERBOSE    [FPS] IR: 0.00 Depth: 30.02 
 24021387 VERBOSE    [FPS] IR: 0.00 Depth: 30.05 
 25003145 VERBOSE    [FPS] IR: 0.00 Depth: 29.98

**Comment by Nan-Orbbec3d-US** [comment]
Hi @iamzhuang , could you also provide the launch file you used? Thank you.

**Comment by iamzhuang** [comment]
I pulled the newest src. and run the "astrapro.launch" of the project .    roslaunch astra_camera astrapro.launch

**Comment by Nan-Orbbec3d-US** [comment]
Ok. Did you plug only one Astra Pro? According to your log, everything works fine. So, let's check
1. both the depth and color images are published and received correctly
2. did you choose the correct `fixed frame`, e.g. `camera_link`. make sure that you are not using `map` or `odom`.

**Comment by Nan-Orbbec3d-US** [comment]
Hi @Thuan98 and @iamzhuang , did you resolve the problem?

**Comment by iamzhuang** [comment]
nothing is resolved yet!    it could display rgb and depth image!!! so ,fixed frame, e.g. camera_link were chose right !   is the camera firmware version too old to support the pointcloud or others?

**Comment by Nan-Orbbec3d-US** [comment]
could you get images from `/camera/rgb/image_rect_color` and `/camera/depth_registered/hw_registered/image_rect_raw`?

**Comment by bool2007** [comment]
> could you get images from `/camera/rgb/image_rect_color` and `/camera/depth_registered/hw_registered/image_rect_raw`?
I have the same problem ,rostopic echo  nothing form the topic /camera/rgb/image_rect_color and /camera/depth_registered/hw_registered/image_rect_raw /camera/depth_registered/points

**Comment by bool2007** [comment]
1180 WARNING    LibraryHandler: Couldn't find function oniDriverStreamConvertC2DCoordinates in libPSLink.so. Stopping
     1192 WARNING    Couldn't use file 'libPSLink.so' as a device driver

I found this warning after I lauch 
@Nan-Orbbec3d-US

**Comment by liamincali** [comment]
Hello!

I would like to report a similar issue regarding the astrapro launch and rviz pointcloud visualization.

Rviz is receiving pointcloud information correctly, but does not display them. 

image_view returns the correct output for all topics camera/depth/... , as well as camera/depth_registered/image_raw, but does NOT display /camera/depth_registered/sw_registered/image_rect_raw. 

Trying to view raw image directly in Rviz results in Camera error: Contains invalid floating point values (nans or infs)

Below attached is the error I am referencing in rviz, as well as an rqt view of active nodes.
![rqt](https://user-images.githubusercontent.com/43684409/64055885-4bb6da00-cb44-11e9-94c8-05413e8eab31.png)
![rviz](https://user-images.githubusercontent.com/43684409/64055887-4e193400-cb44-11e9-9b4e-79b6f086d988.png)

Thanks!

**Comment by Sayter99** [comment]
@liamincali thank you so much! According to your log, I come up with a thing. Does your Astra Pro have intrinsics and extrinsics? You can echo `/camera/rgb/camera_info` and `/camera/depth/camera_info` to get relevant information.

**Comment by Sayter99** [comment]
I don't have Astra Pro now, so I hope you guys can help me with checking the content of your `/camera/*/camera_info`. Now, I infer some of values are nan (not a number) so that the program cannot generate the point cloud. Thus, I fixed this in the latest version. I hope it would fix your problems. If the issue still exists, please let me know and give me more information. Thank you guys.

**Comment by liamincali** [comment]
@Sayter99 I do not have access to the astra pro camera currently either, however I believe that the error is the NaN error that you described as well. I will report back as soon as I am able to test the new version, as well as camera_info if the problem still persists.

Thanks!

**Comment by Sayter99** [comment]
@Thuan98 , @iamzhuang , @liamincali , @bool2007 . Hi guys, could anyone try the fix? Thank you for your time.

**Comment by bool2007** [comment]
> @Thuan98 , @iamzhuang , @liamincali , @bool2007 . Hi guys, could anyone try the fix? Thank you for your time.
@Sayter99  I have try the new version ,with it rviz can display pointcloud
thank you very much!

**Comment by liamincali** [comment]
@Sayter99 my bad, the point cloud is now being displayed. Thanks for the fix!
